name: meditation_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/breathing_exercise.jpeg
    - assets/img/yoga_class.jpeg
    - assets/img/guided_meditation.jpeg
    - assets/img/guided.jpeg
    - assets/img/breathing.jpeg
    - assets/img/healthyrecipess.jpeg
    - assets/img/yoga.jpeg
